coinvn/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path

from . import views

app_name = "homepage"
urlpatterns = [
    path("", views.index, name="index"),
    path("read/<str:headlines>", views.read_news, name="read_news"),
    path("tag/<str:tagtitle>", views.tag_news, name="tag_news"),
    path("choose/<str:categorytitle>", views.category, name="category"),
    path("search", views.search, name="search"),
    path("aboutus", views.aboutus, name="aboutus")
]

homepage/models.py
from django.db import models
from random import randint
from django.contrib.auth.models import User
from datetime import datetime

current_time = datetime.now()
# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=64)
    avatar = models.ImageField(upload_to="author", blank=True)
 
    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=100)
    script = models.CharField(max_length=200, blank=True)
    category_image = models.ImageField(upload_to="dashboard", blank=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class News(models.Model):
    headlines = models.CharField(max_length=150)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=250, blank=True)
    image = models.ImageField(upload_to="news", blank=True, null=True)
    image_square = models.ImageField(upload_to="news square", blank=True, null=True)
    article = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name="author_news")
    main_category = models.ForeignKey(Category, on_delete=models.CASCADE, default='Crypto', related_name="category_news")
    add_time = models.DateTimeField()
    tag = models.ManyToManyField(Tag, blank=True, related_name="newsTag")
    views = models.PositiveIntegerField(default=randint(0,50))
    cmt_count = models.PositiveIntegerField(default=randint(0,5))

    class Meta:
        ordering = ['-views','-add_time']
        verbose_name_plural = "News"

    def tag_titles(self):
        return ', '.join([a.title for a in self.tag.all()])
    tag_titles.short_description = "tag titles"

    def __str__(self):
        return f"{self.headlines}"


class Comment(models.Model):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=200)
    comment = models.TextField()
    cmt_time = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    news = models.ForeignKey(News, blank=True, null=True, on_delete=models.DO_NOTHING, related_name='post_comments')
    avatar = models.ImageField(upload_to="user_ava", blank=True, null=True)

    def __str__(self):
        return f"{self.name}: {self.email}"

homepage/views.py
from markdown2 import Markdown
from django import forms
from secrets import choice
from django.shortcuts import render
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from datetime import date, datetime
from random import randint
import requests

def get_by_headlines(hl):
    try:
        f = News.objects.get(headlines=hl)
        return f
    except:
        return None


def get_by_titles(tt):
    try:
        f = News.objects.get(title=tt)
        return f
    except:
        return None


# Enter your API key here
api_key = "8dbb9d221f0573481a868d614b744b8b"
base_url = "http://api.openweathermap.org/data/2.5/weather?"
city_name = "Hanoi"
complete_url = base_url + "appid=" + api_key + "&q=" + city_name

try:
    response = requests.get(complete_url)
    x = response.json()
    if x["cod"] != "404":
        y = x["main"]
        # key in variable z
        z = x["weather"]
        weather_description = z[0]["description"]
        # to the "temp" key of y
        tempInc = str(round(y["temp"] - 273.15)) + u"\N{DEGREE SIGN}C"
        current_temp = tempInc + "," + city_name
    else:
        current_temp = "Hanoi,Vietnam"
except:
    current_temp = "Hanoi,Vietnam"

# Create your views here.
current_date = date.today().strftime("%a, %B %d, %Y")
now = datetime.now()


def index(request):
    # banner
    four_news = News.objects.all().order_by('-add_time')[0:4]
    categories = Category.objects.all()[0:4]

    # authors
    author_news = []
    if len(Author.objects.all()) < 6:
        authors = Author.objects.all()[:3]
        for author in authors:
            if len(author.author_news.all()) > 1:
                author_news += [author.author_news.all().order_by('-views')[:2]]
    else:
        authors = Author.objects.all()[:6]
        for author in authors:
            if len(author.author_news.all()) > 0:
                author_news += choice(author.author_news.all())

    # general
    category_news = []
    for category in categories:
        if len(category.category_news.all()) > 2:
            category_news.append(
                category.category_news.all().order_by('-views')[2])

    # Hottest
    views_order = News.objects.all().order_by('-views')
    firsttrendingnews = views_order[0]
    banner_of_hottest = firsttrendingnews.main_category.category_image
    next2trendingnews = views_order[1:3]
    last2trendingnews = views_order[3:5]

    # editor choice
    if len(views_order) >= 17:
        left = News.objects.all().order_by('views')[0:6]
    elif len(views_order) >= 12 and len(views_order) < 17:
        left = News.objects.all().order_by('views')[0:3]
    recommended = [[], []]
    views_order = []
    for i in range(len(left)):
        j = i // 3
        recommended[j].append(left[i])

    five_latest = News.objects.all().order_by('-add_time')[:5]

    return render(request, 'homepage/index.html', {
        "current_date": current_date, "current_temp": current_temp,
        "four_news": four_news,
        "category_news": category_news,
        "author_news": author_news,
        "firsttrendingnews": firsttrendingnews, "banner_of_hottest": banner_of_hottest,
        "next2trendingnews": next2trendingnews,
        "last2trendingnews": last2trendingnews,
        "recommended": recommended,
        "five_latest": five_latest,
    })


def category(request, categorytitle):
    try:
        thiscategory = Category.objects.get(title=categorytitle)
    except:
        message = "Chủ đề " + categorytitle + " không tồn tại"
        return render(request, 'homepage/error.html', {
            "code": 404,
            "suggestion": False,
            "message": message,
        })
    primary_choice = choice(thiscategory.category_news.all()[:3])
    all_news = thiscategory.category_news.exclude(
        headlines=primary_choice.headlines)
    firttwos = all_news[:2]
    nexttwos = all_news[2:4]
    left = all_news[4:]
    if len(left) > 16:
        left = all_news[4:20]
    next_news = [[], [], [], []]
    if left:
        for i in range(len(left)):
            j = i // 4
            next_news[j].append(left[i])

    return render(request, 'homepage/secondary.html', {
        "current_date": current_date, "current_temp": current_temp,
        "primary_choice": primary_choice, "firttwos": firttwos, "nexttwos": nexttwos,
        "next_news": next_news,
        "category": thiscategory,
    })

def read_news(request, headlines):
    markdowner = Markdown()
    news = get_by_headlines(headlines)
    if news is None:
        message = "Không có bài đăng nào với tiêu đề: " + headlines
        return render(request, 'homepage/error.html', {
            "code": 404,
            "suggestion": False,
            "message": message
        })
    content = news.article
    author = news.author
    newest = News.objects.all().order_by('-add_time').first()
    trendingnews = []
    for tnews in News.objects.all().order_by('-views'):
        if tnews.add_time.day == newest.add_time.day or tnews.add_time.day == newest.add_time.day - 1:
            trendingnews.append(tnews)
        if len(trendingnews) >= 4:
            break
    news_tags = news.tag.all()

    # Comments
    comments = Comment.objects.filter(news=news).filter(status=True)
    for comment in comments:
        comment.day_time = comment.cmt_time.strftime('%d %B %Y')
    # Related news
    related_news = []
    for tag in news_tags:
        for n in Tag.objects.get(title=tag).newsTag.all().exclude(headlines=news.headlines):
            if n not in related_news:
                related_news.append(n)
        if len(related_news) >= 6:
            break
    message = ""
    # Post a comment
    if request.method == "POST":
        news.cmt_count += 1
        news.save()
        if not request.POST['name'] or not request.POST['email'] or not request.POST['message']:
            return render(request, 'homepage/error.html', {'code': 401, "message": "Bạn phải nhập tên, email và nội dung bình luận!"})
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        try:
            avatar = request.FILES["user_ava"]
        except:
            avatar = ""
        Comment.objects.create(name=name, email=email, comment=comment, news=news, avatar=avatar)
        message = "Bình luận đã được gửi đi, trong quá trình cần kiểm duyệt"
        return HttpResponseRedirect(reverse("homepage:read_news", args=(headlines,)))
    
    # Recent
    recent_news = News.objects.all().order_by('-add_time')[:4]
    # Popular
    popular_news = News.objects.all().order_by('-views')[:4]
    # Tags
    if randint(0,1) == 0:
        tags = Tag.objects.annotate(news_count=Count('newsTag')).order_by('-news_count')[:11]
    else:
        tags = Tag.objects.annotate(news_count=Count('newsTag')).order_by('news_count')[:12]
    news.views += 1
    news.save()
    return render(request, 'homepage/newsdetails.html', {
        "current_date": current_date, "current_temp": current_temp,
        "trendingnews": trendingnews,
        "news": news,
        "content": markdowner.convert(content),
        "author": author,
        "message": message,
        "news_tags": news_tags,
        "comments": comments,
        "related_news": related_news,
        "recent_news": recent_news,
        "popular_news": popular_news,
        "tags": tags
    })


def search(request):
    r = request.GET.get("r", "")
    subStringEntries = []
    for entry in News.objects.all():
        if r.upper() in entry.headlines.upper() or r.upper() in entry.title.upper() or r.upper() in entry.main_category.title.upper() or r.upper() in entry.author.name.upper():
            subStringEntries.append(entry)

    if get_by_headlines(r) is not None:
        return HttpResponseRedirect("read/" + r)
    if get_by_titles(r) is not None:
        return HttpResponseRedirect("read/" + get_by_titles(r).headlines)
    elif subStringEntries:
        first_result = subStringEntries.pop(0)
        message = "Kết quả tìm kiếm cho " + r
        return render(request, "homepage/results.html", {
            "current_date": current_date, "current_temp": current_temp,
            "first_result": first_result,
            "results": subStringEntries,
            "message": message,
        })
    else:
        message = "Không kết quả tìm kiếm nào phù hợp với " + r + " !"
        return render(request, 'homepage/error.html', {
            "current_date": current_date, "current_temp": current_temp,
            "code": "",
            "suggestion": True,
            "message": message,
        })


def aboutus(request):
    return render(request, 'homepage/aboutus.html')


def tag_news(request, tagtitle):
    found = False
    for tag in Tag.objects.all():
        if tagtitle.upper() in tag.title.upper():
            tagtitle = tag.title
            found = True
    tagnews = Tag.objects.get(title=tagtitle).newsTag.all()
    if not found or not tagnews:
        message = "Không có kết quả tìm kiếm nào phù hợp với Tag: " + tagtitle + " !"
        return render(request, 'homepage/error.html', {
            "current_date": current_date, "current_temp": current_temp,
            "code": "",
            "suggestion": True,
            "message": message,
        })
    else:
        first_result = tagnews.first()
        results_left = tagnews[1:]
        message = "Kết quả với Tag: " + tagtitle
        return render(request, 'homepage/results.html', {
            "current_date": current_date, "current_temp": current_temp,
            "first_result": first_result,
            "results": results_left,
            "message": message,
        })

homepage/templates/homepage/aboutus.html
{% extends 'homepage/layout.html' %}
{% block title %}Trang Chủ{% endblock %}
{% block body %}
{% load static %}
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="text-center">
        <h1 class="text-center mt-5">
          Về Chúng Tôi
        </h1>
        <p class="text-secondary fs-15 mb-5 pb-3">
          Một trang tóm tắt đơn giản ngắn gọn mọi thứ về chúng tôi
        </p>
      </div>
    </div>
  </div>
  <div class="contact-wrap">
    <div class="row">
      <div class="col-lg-6  mb-5 mb-sm-2">
        <div class="position-relative image-hover">
          <img src="{% static 'homepage/images/logofull.png' %}" class="img-fluid" alt="world-news" />
        </div>
      </div>
      <div class="col-lg-6 mb-2 mb-lg-2">
        <div class="row">
          <div class="col-sm-12  mb-2 mb-lg-2">
            <h1>NHIỆM VỤ CHÚNG TÔI</h1>
            <p class="mb-3">Tại Sao Chọn Chúng Tôi?</p>
            <p class="mb-4">
              Coin98 VN là trang chia sẻ tin tức kiến thức, đầu tư hàng đầu việt nam về tiền ảo, tiền đIện tử,
              cryptocurrency. Đến với Coin98 VN bạn có thể học tập, nghiên cứu cũng như nâng cao kỹ năng đầu tư tiền
              điện tử cũng như học nhiều cách kiếm tiền trên mạng.
            </p>
            <p class="mb-4">
              Coin98 VN is Vietnam's leading investment and knowledge sharing site about virtual currencies, cryptocurrencies,
               cryptocurrency. Coming to Coin98 VN you can study, research as well as improve money investment skills
               electronics as well as learn many ways to make money online. (make money online)
            </p>
            <p class="fs-15 font-weight-600">
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

homepage/templates/homepage/error.html
{% extends 'homepage/layout.html' %}
{% block title %}Not Found{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-warning" role="alert">{{ message }}</div>
            {% if suggestion %}
            <h2>Gợi Ý</h2>
            <div class="list-group">
                <button type="button" class="list-group-item list-group-item-action">
                    Hãy chắn chắn ràng tất cả những từ đều được đánh vần đúng.
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    Hãy thử các từ khóa khác nhau.
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    Thử những từ khóa thông thường hơn.
                </button>
                <button type="button" class="list-group-item list-group-item-action">
                    Hãy thử ít từ khóa hơn.
                </button>
            </div>
            {% endif %}
            <div class="error-wrap">
                <div class="error-title">
                    {{code}}
                </div>
                <div class="error-sub-title">
                    Oops! Trang mà bạn tìm kiếm không tồn tại
                </div>
                <p>Có thể sử dụng các mục trên thanh điều hướng hoặc tìm kiếm.</p>

                <div class="search-container"  style="border-radius: 10px;">
                    <form action="{% url 'homepage:search' %}" method="get" class="d-flex">
                        <input type="text" placeholder="Search" name="r" />
                        <button type="submit"><i class="mdi mdi-magnify"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

homepage/templates/homepage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
  <!-- Required meta tags -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>{% block title %}{% endblock %} | Coin98 VN</title>
  <!-- plugin css for this page -->
  <link rel="stylesheet" href="{% static 'homepage/vendors/mdi/css/materialdesignicons.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'homepage/vendors/aos/dist/aos.css/aos.css' %}"/>
  <link rel="stylesheet" href="{% static 'homepage/vendors/owl.carousel/dist/assets/owl.carousel.min.css' %}"/>
  <link rel="stylesheet" href="{% static 'homepage/vendors/owl.carousel/dist/assets/owl.theme.default.min.css' %}"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- End plugin css for this page -->
  <link rel="shortcut icon" href="{% static 'homepage/images/favicon.png' %}" />
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'homepage/css/style.css' %}">
  <!-- endinject -->
</head>

<body>
  <div class="loader">
    <div class="circle"></div>
    <div class="circle"></div>
  </div>
  <div class="container-scroller">
    <div class="main-panel">
      <header id="header">
        <div class="container">
          <!-- partial:partials/_navbar.html -->
          <nav class="navbar navbar-expand-lg navbar-light">
            <div class="d-flex justify-content-between align-items-center navbar-top">
              <ul class="navbar-left">
                <li>{{ current_date }}</li>
              </ul>
              <div>
                <a class="navbar-brand" href="{% url 'homepage:aboutus' %}"><img src="{% static 'homepage/images/logotext1.svg' %}" alt="Logo CoinVN" /></a>
              </div>
              <div class="d-flex">
                <ul class="navbar-right">
                  <li>{{ current_temp }}</li>
                </ul>
                <ul class="social-media">
                  <li>
                    <a href="#">
                      <i class="mdi mdi-instagram"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://www.facebook.com/dangquang211102/">
                      <i class="mdi mdi-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="mdi mdi-youtube"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="mdi mdi-twitter"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="navbar-bottom-menu">
              <button class="navbar-toggler" type="button" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="navbar-collapse justify-content-center collapse" id="navbarSupportedContent">
                <ul class="navbar-nav d-lg-flex justify-content-between align-items-center">
                  <li>
                    <button class="navbar-close">
                      <i class="mdi mdi-close"></i>
                    </button>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'homepage:index' %}">Trang Chủ</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:category' categorytitle="Crypto" %}">Cryptocurrency</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:category' categorytitle="Game Defi" %}">Game Defi</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:category' categorytitle="Kiến Thức" %}">Kiến Thức</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:category' categorytitle="Hướng Dẫn" %}">Hướng Dẫn</a>
                  </li>
                  <li class="nav-item">
                    <form action="{% url 'homepage:search' %}" method="get" style="display: flex; justify-content: center;">
                      <input style="transform: translateY(50%);" class="mr-2 form-control col-lg-10 col-md-8 col-sm-4 form-control-sm" type="text"
                        placeholder="Search" value="" name="r" maxlength="250"/>
                      <a class="nav-link" onclick="this.parentNode.submit();"><i id="magnify-icon" class="mdi mdi-magnify"></i></a>
                    </form>
                  </li>
                </ul>
              </div>
            </div>
          </nav>

          <!-- partial -->
        </div>
      </header>
      <!-- main-panel ends -->
      <!-- container-scroller ends -->
      {% block body %}
      {% endblock %}
      <!-- partial:partials/_footer.html -->
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="border-top"></div>
            </div>
            <div class="col-sm-3 col-lg-3">
              <ul class="footer-vertical-nav">
                <li class="menu-title"><a href="{% url 'homepage:index' %}" class="text-dark">Trang Chủ</a></li>
                <li><a href="{% url 'homepage:tag_news' 'GAFI' %}" class="text-dark">GAFI</a></li>
                <li><a href="{% url 'homepage:tag_news' 'binance' %}" class="text-dark">Binance</a></li>
              </ul>
            </div>
            <div class="col-sm-3 col-lg-3">
              <ul class="footer-vertical-nav">
                <li class="menu-title"><a href="{% url 'homepage:tag_news' tagtitle='gamefi' %}" class="text-dark">Game Defi</a></li>
                <li><a href="{% url 'homepage:tag_news' 'bybit' %}" class="text-dark">Sàn Bybit</a></li>
                <li><a href="{% url 'homepage:category' 'Kiến Thức' %}" class="text-dark">Kiến Thức</a></li>
              </ul>
            </div>
            <div class="col-sm-3 col-lg-3">
              <ul class="footer-vertical-nav">
                <li class="menu-title"><a href="{% url 'homepage:category' 'Crypto' %}" class="text-dark">Crypto</a></li>
                <li><a href="{% url 'homepage:tag_news' 'love token' %}" class="text-dark">Love Token</a></li>
                <li><a href="{% url 'homepage:tag_news' 'là gì' %}" class="text-dark">Định nghĩa</a></li>
              </ul>
            </div>
            <div class="col-sm-3 col-lg-3">
              <ul class="footer-vertical-nav">
                <li class="menu-title"><a href="{% url 'homepage:category' 'Hướng Dẫn' %}" class="text-dark">Hướng Dẫn</a></li>
                <li><a href="{% url 'homepage:aboutus' %}" class="text-dark">Về Chúng Tôi</a></li>
                <li><a href="#" class="text-dark">Liên Hệ</a></li>
              </ul>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="d-flex justify-content-between">
                <div class="col-6">
                  <img src="{% static 'homepage/images/favicon.png' %}" class="logo-img" alt="logo" />
                  <img src="{% static 'homepage/images/logotext.svg' %}" class="footer-logo" alt="logo" />
                </div>
                <div class="d-flex justify-content-end footer-social">
                  <h5 class="m-0 font-weight-600 mr-3 d-none d-lg-flex">Follow us on</h5>
                  <ul class="social-media">
                    <li>
                      <a href="#">
                        <i class="mdi mdi-instagram"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-youtube"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-twitter"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <div class="d-lg-flex justify-content-between align-items-center border-top mt-5 footer-bottom">
                <ul class="footer-horizontal-menu">
                  <li><a href="{% url 'homepage:aboutus' %}" class="text-dark">About Us</a></li>
                  <li><a href="#" class="text-dark">Contact Us</a></li>
                </ul>
                <p class="font-weight-medium">
                  © 2022 @ Coin98 VN,
                  Inc.All Rights Reserved.
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>

      <!-- partial -->
    </div>
  </div>
  <!-- inject:js -->
  <script src="{% static 'homepage/vendors/js/vendor.bundle.base.js' %}"></script>
  <!-- endinject -->
  <!-- plugin js for this page -->
  <script src="{% static 'homepage/vendors/owl.carousel/dist/owl.carousel.min.js' %}"></script>
  <!-- End plugin js for this page -->
  <!-- Custom js for this page-->
  {% block script %}{% endblock %}
  <script src="{% static 'homepage/js/slider.js' %}"></script>
  <script src="{% static 'homepage/js/demo.js' %}"></script>
  <!-- End custom js for this page-->
  <script src="{% static 'homepage/js/jquery.ticker.js' %}"></script>
  <script src="{% static 'homepage/js/site.js' %}"></script>

</body>

</html>

homepage/templates/homepage/results.html
{% extends 'homepage/layout.html' %}
{% block title %}Search Results{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-success" style="margin-top: 20px;" role="alert">
                {{ message }}
            </div>
            <div class="news-post-wrapper">
                <div class="news-post-wrapper-sm ">
                    <a href="{% url 'homepage:read_news' headlines=first_result.headlines %}"><h1 class="text-center">
                        {{ first_result.headlines }}
                    </h1></a>
                    <div class="text-center">
                        <a href="{% url 'homepage:category' categorytitle=first_result.main_category %}"
                            class="btn btn-dark font-weight-bold mb-4">{{ first_result.main_category|upper }}</a>
                    </div>
                    <p class="fs-15 d-flex justify-content-center align-items-center m-0">
                        <img src="{% static 'homepage/images' %}/{{ first_result.author.avatar }}" alt="author-ava"
                            class="img-xs img-rounded mr-2" />
                        {{ first_result.author }} | {{ first_result.add_time|date:'M d, Y' }}
                    </p>
                    <p class="pt-4 pb-4">
                        {{ first_result.title }}. {{ first_result.subtitle }}
                    </p>
                </div>
                <a href="{% url 'homepage:read_news' headlines=first_result.headlines %}">
                    <img src="{% static 'homepage/images' %}/{{ first_result.image }}" width="100%" alt="news" class="img-fluid mb-4" />
                </a>
                <div class="news-post-wrapper-sm mt-5">
                    {% for news in results %}
                    <div class="border-top py-5">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="position-relative image-hover">
                                    <a href="{% url 'homepage:read_news' headlines=first_result.headlines %}">
                                        <img src="{% static 'homepage/images' %}/{{ news.image_square }}" alt="news"
                                            class="img-fluid" />
                                    </a>
                                    <span class="thumb-title">{{ news.main_category|upper }}</span>
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <div class="position-relative image-hover">
                                    <a href="{% url 'homepage:read_news' headlines=first_result.headlines %}">
                                        <h2 class="font-weight-normal-2">
                                            {{ news.headlines }}
                                        </h2>
                                    </a>
                                    <p class="fs-15">{{ news.author }} | {{ news.add_time }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}